server:
  port: 8761
spring:
  application:
    name: snailmall-eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
  server:
    enable-self-preservation: false